#!/bin/bash

## Generates a basic autotools base structure 
# $1: foldername
## 
make_autotools_skeleton(){
	local NAME="florian mayer"
	local MAIL="mayer.florian@web.de"

	if [ ! -d "$1" ]; then
		echo Kein Verzeichnis angegeben!
		return 1	
	fi

	mkdir "$1"
	cd "$1"
	touch Makefile.am
	touch configure.in

	#generate needed files
	touch NEWS README AUTHORS ChangeLog
	cat > NEWS << EOF 
Put your news here
EOF

	cat > README << EOF
This package has been generated by a shell function
EOF

	cat > ChangeLog << EOF
$(date "+%Y%m%d") $NAME $MAIL
	* <add first entry>

EOF

	cat > AUTHORS << EOF
Author: $NAME
E-Mail: $MAIL
EOF
	
	#populate Makefile.am
	echo "bin_PROGRAMS = <here>" >> Makefile.am
	echo "<here>_SOURCES = <sources>" >> Makefile.am

	cat > configure.ac << EOF
AC_PREREQ(2.59)

dnl Standard boilerplate code
AC_INIT([<your projectname>], [<version>], [$MAIL])
AM_INIT_AUTOMACE([1.9 gnu])

dnl Define additional options that go into the configure script
AC_ARG_WITH([<package>], [<help-string>], [<action if gieven>], [<action if not>])
AC_ARG_ENABLE([<yourarg>], [<aewr>]) 

dnl Check for programs needed by one of the programs being build, or by the build process
AC_CHECK_PROG
AC_PATH_TOOL

dnl Check for libraries

dnl Check for headers

dnl Check for typedefs and structures

dnl Check for specific functions

dnl Outputting configure
AC_OUTPUT
EOF
	
}
