echo "[~/.bash_profile] calling ~/.profile"
. ~/.profile

##
# Your previous /Users/florian/.bash_profile file was backed up as /Users/florian/.bash_profile.macports-saved_2014-02-09_at_00:28:35
##

# MacPorts Installer addition on 2014-02-09_at_00:28:35: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

